from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(626, 545)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 40, 281, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 40, 251, 21))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 80, 251, 21))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 120, 61, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(120, 240, 21, 21))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 280, 251, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(10, 200, 251, 21))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(200, 200, 61, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(10, 160, 251, 21))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 160, 61, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(320, 40, 261, 351))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(60, 430, 56, 17))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 430, 56, 17))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_2.setTitle(_translate("Dialog", "Tool Specification"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Tool Name"))
        self.plainTextEdit_2.setPlainText(_translate("Dialog", "Tool Description"))
        self.pushButton_3.setText(_translate("Dialog", "Tool Path"))
        self.plainTextEdit_5.setPlainText(_translate("Dialog", "OR"))
        self.pushButton_5.setText(_translate("Dialog", "Tool Specification File"))
        self.plainTextEdit_4.setPlainText(_translate("Dialog", "Output Data Specification"))
        self.pushButton_6.setText(_translate("Dialog", "+"))
        self.plainTextEdit_3.setPlainText(_translate("Dialog", "Option and Argument"))
        self.pushButton_4.setText(_translate("Dialog", "+"))
        self.groupBox_4.setTitle(_translate("Dialog", "Tool Dependency"))
        self.pushButton.setText(_translate("Dialog", "Save"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
