# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RunArea.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from DetailedViewRun import*

class Ui_MainWindowRun(object):
    def openWindow(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindowViewRun()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 671)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 751, 141))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setGeometry(QtCore.QRect(610, 50, 71, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 131, 31))
        self.comboBox.setObjectName("comboBox")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(280, 40, 131, 31))
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_10.setGeometry(QtCore.QRect(410, 40, 121, 31))
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 40, 71, 16))
        self.label.setObjectName("label")
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_9.setGeometry(QtCore.QRect(150, 40, 131, 31))
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.plainTextEdit_12 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_12.setGeometry(QtCore.QRect(150, 70, 131, 31))
        self.plainTextEdit_12.setPlainText("")
        self.plainTextEdit_12.setObjectName("plainTextEdit_12")
        self.plainTextEdit_13 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_13.setGeometry(QtCore.QRect(280, 70, 131, 31))
        self.plainTextEdit_13.setPlainText("")
        self.plainTextEdit_13.setObjectName("plainTextEdit_13")
        self.plainTextEdit_11 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_11.setGeometry(QtCore.QRect(20, 70, 131, 31))
        self.plainTextEdit_11.setPlainText("")
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")
        self.plainTextEdit_14 = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_14.setGeometry(QtCore.QRect(410, 70, 121, 31))
        self.plainTextEdit_14.setPlainText("")
        self.plainTextEdit_14.setObjectName("plainTextEdit_14")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(410, 70, 41, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(450, 70, 41, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(490, 70, 41, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 190, 751, 301))
        self.groupBox_2.setObjectName("groupBox_2")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(10, 30, 251, 31))
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.plainTextEdit_15 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_15.setGeometry(QtCore.QRect(10, 70, 251, 91))
        self.plainTextEdit_15.setObjectName("plainTextEdit_15")
        self.plainTextEdit_16 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_16.setGeometry(QtCore.QRect(10, 170, 251, 51))
        self.plainTextEdit_16.setObjectName("plainTextEdit_16")
        self.plainTextEdit_17 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_17.setGeometry(QtCore.QRect(10, 230, 251, 51))
        self.plainTextEdit_17.setObjectName("plainTextEdit_17")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(460, 30, 161, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_14.setGeometry(QtCore.QRect(650, 30, 71, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(470, 40, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(580, 90, 35, 10))
        self.label_3.setObjectName("label_3")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_16.setGeometry(QtCore.QRect(530, 260, 71, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_17.setGeometry(QtCore.QRect(450, 260, 71, 31))
        self.pushButton_17.setObjectName("pushButton_17")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.groupBox_2)
        self.commandLinkButton.setGeometry(QtCore.QRect(610, 250, 141, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")

        self.commandLinkButton.clicked.connect(self.openWindow)

        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(450, 120, 261, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowser_7.setGeometry(QtCore.QRect(10, 20, 241, 71))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_15.setGeometry(QtCore.QRect(380, 180, 71, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.groupBox_4.raise_()
        self.plainTextEdit_8.raise_()
        self.plainTextEdit_15.raise_()
        self.plainTextEdit_16.raise_()
        self.plainTextEdit_17.raise_()
        self.comboBox_2.raise_()
        self.pushButton_14.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.pushButton_16.raise_()
        self.pushButton_17.raise_()
        self.commandLinkButton.raise_()
        self.pushButton_15.raise_()
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 500, 751, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 71, 20))
        self.label_5.setObjectName("label_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser.setGeometry(QtCore.QRect(110, 30, 221, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 91, 20))
        self.label_6.setObjectName("label_6")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser_2.setGeometry(QtCore.QRect(110, 70, 221, 71))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.fontComboBox = QtWidgets.QFontComboBox(self.groupBox_3)
        self.fontComboBox.setGeometry(QtCore.QRect(480, 30, 221, 22))
        self.fontComboBox.setObjectName("fontComboBox")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(580, 60, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_3.setGeometry(QtCore.QRect(490, 80, 61, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_4.setGeometry(QtCore.QRect(560, 80, 61, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.remove_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.remove_btn.setGeometry(QtCore.QRect(630, 80, 75, 23))
        self.remove_btn.setObjectName("remove_btn")
        self.generate_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.generate_btn.setGeometry(QtCore.QRect(560, 120, 75, 23))
        self.generate_btn.setObjectName("generate_btn")
        self.cancel_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.cancel_btn.setGeometry(QtCore.QRect(640, 120, 75, 23))
        self.cancel_btn.setObjectName("cancel_btn")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(720, 10, 21, 21))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Run List"))
        self.pushButton_13.setText(_translate("MainWindow", "Add"))
        self.plainTextEdit_7.setPlainText(_translate("MainWindow", "Result with Timestamp"))
        self.plainTextEdit_10.setPlainText(_translate("MainWindow", "Control"))
        self.label.setText(_translate("MainWindow", "Name of Run"))
        self.plainTextEdit_9.setPlainText(_translate("MainWindow", "Description of Run"))
        self.pushButton_9.setText(_translate("MainWindow", "Play"))
        self.pushButton_10.setText(_translate("MainWindow", "Pause"))
        self.pushButton_11.setText(_translate("MainWindow", "Stop"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Configuration of the Selected Run"))
        self.plainTextEdit_8.setPlainText(_translate("MainWindow", "Run Name"))
        self.plainTextEdit_15.setPlainText(_translate("MainWindow", "Run Description"))
        self.plainTextEdit_16.setPlainText(_translate("MainWindow", "Whitelisted IP Target"))
        self.plainTextEdit_17.setPlainText(_translate("MainWindow", "Blacklisted IP Target"))
        self.pushButton_14.setText(_translate("MainWindow", "Add"))
        self.label_4.setText(_translate("MainWindow", "Scan Type"))
        self.label_3.setText(_translate("MainWindow", "OR"))
        self.pushButton_16.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_17.setText(_translate("MainWindow", "Save"))
        self.commandLinkButton.setText(_translate("MainWindow", "Detailed View"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Run Configuration File"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_15.setText(_translate("MainWindow", "Browse"))
        self.groupBox_3.setTitle(_translate("MainWindow", "XML Report"))
        self.label_5.setText(_translate("MainWindow", "Report Name"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Report Name goes here</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Report Description"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Description of Report.....</p></body></html>"))
        self.fontComboBox.setCurrentText(_translate("MainWindow", "Run"))
        self.label_7.setText(_translate("MainWindow", "OR"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Run"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Scan"))
        self.remove_btn.setText(_translate("MainWindow", "Remove"))
        self.generate_btn.setText(_translate("MainWindow", "Generate"))
        self.cancel_btn.setText(_translate("MainWindow", "Cancel"))
        self.pushButton.setText(_translate("MainWindow", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowRun()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
